import { CollectionConfig } from 'payload'
import {
  lexicalEditor,
  BoldFeature,
  ItalicFeature,
  UnderlineFeature,
  StrikethroughFeature,
  UnorderedListFeature,
  OrderedListFeature,
  HeadingFeature,
  LinkFeature,
  ParagraphFeature,
} from '@payloadcms/richtext-lexical'

const contentEditor = lexicalEditor({
  features: [
    ParagraphFeature(),
    BoldFeature(),
    ItalicFeature(),
    UnderlineFeature(),
    StrikethroughFeature(),
    HeadingFeature({ enabledHeadingSizes: ['h2', 'h3', 'h4'] }),
    UnorderedListFeature(),
    OrderedListFeature(),
    LinkFeature(),
  ],
})

export const CaseStudies: CollectionConfig = {
  slug: 'case-studies',
  labels: {
    singular: 'Case Study',
    plural: 'Case Studies',
  },
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'industry', 'technology', 'slug'],
    group: 'Case Studies',
  },
  access: {
    read: () => true,
    create: () => true,
    update: () => true,
    delete: () => true,
  },
  fields: [
    {
      type: 'group',
      name: 'meta',
      label: 'SEO Meta',
      fields: [
        {
          name: 'metaTitle',
          label: 'Meta Title',
          type: 'text',
          required: true,
        },
        {
          name: 'metaDescription',
          label: 'Meta Description',
          type: 'textarea',
          required: true,
          maxLength: 160,
        },
      ],
    },
    {
      name: 'title',
      label: 'Title',
      type: 'text',
      required: true,
    },
    {
      name: 'content',
      label: 'Content',
      type: 'group',
      required: true,
      fields: [
        {
          name: 'paraOne',
          label: 'Problem Statement',
          required: true,
          type: 'richText',
          editor: contentEditor,
        },
        {
          name: 'paraTwo',
          label: 'Our Solution',
          required: true,
          type: 'richText',
          editor: contentEditor,
        },
        {
          name: 'paraThree',
          label: 'Insights & Outcomes',
          required: true,
          type: 'richText',
          editor: contentEditor,
        },
      ],
    },
    {
      name: 'counterData',
      label: 'Counter Data',
      required: true,
      type: 'array',
      labels: {
        singular: 'Counter Item',
        plural: 'Counter Items',
      },
      minRows: 3,
      maxRows: 3,
      fields: [
        {
          name: 'count',
          label: 'Count Value',
          type: 'text',
          required: true,
          admin: {
            description: 'Example: 40%, 3X, 100+, etc.',
          },
        },
        {
          name: 'text',
          label: 'Description',
          type: 'textarea',
          required: true,
        },
      ],
    },
    {
      name: 'displayImage',
      label: 'Display Image',
      required: false,
      type: 'upload',
      relationTo: 'caseStudyMedia',
    },
    {
      name: 'bannerImage',
      label: 'Banner Image',
      required: false,
      type: 'upload',
      relationTo: 'caseStudyMedia',
    },
    {
      name: 'studyImages',
      label: 'Study Images',
      required: false,
      type: 'group',
      fields: [
        {
          name: 'image01',
          label: 'Image 01',
          required: false,
          type: 'upload',
          relationTo: 'caseStudyMedia',
        },
        {
          name: 'image02',
          label: 'Image 02',
          required: false,
          type: 'upload',
          relationTo: 'caseStudyMedia',
        },
        {
          name: 'image03',
          label: 'Image 03',
          required: false,
          type: 'upload',
          relationTo: 'caseStudyMedia',
        },
      ],
    },
    {
      name: 'industry',
      label: 'Industry',
      type: 'select',
      required: true,
      options: [
        { label: 'Automotive', value: 'automotive' },
        { label: 'Energy', value: 'energy' },
        { label: 'Healthcare', value: 'healthcare' },
        { label: 'Manufacturing', value: 'manufacturing' },
        { label: 'Technology', value: 'technology' },
      ],
    },
    {
      name: 'technology',
      label: 'Key Technologies (select all that apply)',
      required: false,
      type: 'select',
      hasMany: true,
      admin: {
        description: 'Select one or more technologies used in this case study.',
      },
      options: [
        { label: 'Vision AI', value: 'vision-ai' },
        { label: 'Machine Learning', value: 'machine-learning' },
        { label: 'Generative AI', value: 'generative-ai' },
        { label: 'Computer Vision', value: 'computer-vision' },
        { label: 'Data Analytics', value: 'data-analytics' },
        { label: 'Real-Time Analytics', value: 'real-time-analytics' },
        { label: 'IoT', value: 'iot' },
        { label: 'MQTT', value: 'mqtt' },
        { label: 'Bluetooth / BLE', value: 'bluetooth-ble' },
        { label: 'Zigbee', value: 'zigbee' },
        { label: 'CAN Bus', value: 'can-bus' },
        { label: 'MODBUS', value: 'modbus' },
        { label: 'Wi-Fi / 802.11', value: 'wifi-802-11' },
        { label: 'LTE / 5G', value: 'lte-5g' },
        { label: 'Embedded Systems', value: 'embedded-systems' },
        { label: 'Zephyr RTOS', value: 'zephyr-rtos' },
        { label: 'FreeRTOS', value: 'freertos' },
        { label: 'Android (Embedded)', value: 'android-embedded' },
        { label: 'Linux / Yocto', value: 'linux-yocto' },
        { label: 'ROS / ROS2', value: 'ros-ros2' },
        { label: 'AWS', value: 'aws' },
        { label: 'Azure', value: 'azure' },
        { label: 'Google Cloud', value: 'google-cloud' },
        { label: 'Cloud Engineering', value: 'cloud-engineering' },
        { label: 'Edge Computing', value: 'edge-computing' },
        { label: 'Docker / Kubernetes', value: 'docker-kubernetes' },
        { label: 'EV Vehicles', value: 'ev-vehicles' },
        { label: 'Energy Consumption', value: 'energy-consumption' },
        { label: 'Digital Twin', value: 'digital-twin' },
        { label: 'Robotics & Automation', value: 'robotics-automation' },
        { label: 'Autonomous Systems', value: 'autonomous-systems' },
        { label: 'Predictive Maintenance', value: 'predictive-maintenance' },
        { label: 'Fleet Management', value: 'fleet-management' },
        { label: 'SCADA / Industrial Control', value: 'scada-industrial-control' },
        { label: 'Cybersecurity', value: 'cybersecurity' },
        { label: 'API Integration', value: 'api-integration' },
      ],
    },
    {
      name: 'tag',
      label: 'Category Tag',
      type: 'select',
      required: true,
      options: [
        { label: 'EV Charging', value: 'EV Charging' },
        { label: 'Energy Management', value: 'Energy Management' },
      ],
      admin: {
        position: 'sidebar',
        description: 'Used for filtering on the case studies listing page.',
      },
    },
    {
      name: 'client',
      label: 'Client',
      type: 'text',
      required: true,
      admin: {
        description: 'e.g. "Major multinational with 500+ vehicle fleet"',
      },
    },
    {
      name: 'location',
      label: 'Location',
      type: 'text',
      required: true,
      admin: {
        description: 'e.g. "Greece", "Global (12 campuses)"',
      },
    },
    {
      name: 'summary',
      label: 'Summary',
      type: 'textarea',
      required: true,
      admin: {
        description: 'Short summary shown on the case study listing cards.',
      },
    },
    {
      name: 'testimonial',
      label: 'Testimonial',
      type: 'group',
      fields: [
        {
          name: 'quote',
          label: 'Quote',
          type: 'textarea',
        },
        {
          name: 'author',
          label: 'Author',
          type: 'text',
        },
        {
          name: 'role',
          label: 'Role / Title',
          type: 'text',
        },
      ],
    },
    {
      name: 'slug',
      label: 'Slug',
      type: 'text',
      unique: true,
      required: true,
      admin: {
        position: 'sidebar',
      },
    },
  ],
}
